os: linux
language: generic
dist: melodic

jobs:
  include:
    - name: ROS tests
      services:
        - docker
      env:
        - ROS_DISTRO="melodic"
        - UPSTREAM_WORKSPACE="upstream.repos"
        # Pass environment so codecov works
        - DOCKER_RUN_OPTS="$ci_env"
        # Configure properly so we can run coverage
        - CMAKE_ARGS="-DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug"
        # Run coverage testing
        - AFTER_SCRIPT="./.coverage.sh"
      install:
        - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
      script:
        - ci_env=`bash <(curl -s https://codecov.io/env)`
        - .industrial_ci/travis.sh
